firstproject/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

firstproject/basketapp/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
 ]

firstproject/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:books_id>/', basketapp.add, name='add'),
    path('add/<int:books_basket_id>/', basketapp.remove, name='remove'),
 ]

firstproject/firstproject/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),

    path('auth', include('authapp.urls', namespace='auth')),

    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', admin.site.urls),
]

firstproject/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.catalog, name='catalog'),

    path('catalog/category/<int:category_pk>/', mainapp.catalog_page, name='catalog_page'),
    path('catalog/books/<int:books_pk>/', mainapp.books_page, name='books_page'),
]

firstproject/basketapp/models.py
from django.contrib.auth.models import User
from django.db import models
from mainapp.models import Books

class BookBasket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    books = models.ForeignKey(Books, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}: {self.books.name}'

    def to_html(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}</i>: <b>{self.books.name}</b>'
# Create your models here.

firstproject/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

class Books(models.Model):
    category = models.ForeignKey(ProductCategory,
                                 on_delete=models.CASCADE)
    name = models.CharField('Название', max_length=200)
    desc = models.TextField('Описание', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

firstproject/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.forms import User

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name',
                'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

firstproject/authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegisterForm()

        context = {
            'page_title': 'регистрация',
            'form': form,
        }
        return render(request, 'authapp/register.html', context)

firstproject/basketapp/views.py
from django.shortcuts import render
from django.urls import reverse
from mainapp.models import Books

def index(request):
    item = BookBasket.objects.filter(user =request.user)
    context = {
        'object_list': item,
    }
    return render(request, 'basketapp/basket.html', context)

def add (request, books_id):
    books = Books.objects.get(pk=books_id)
    BookBasket.objects.get_or_create(
       user=request.user,
       books=books
    )

def remove(request, books_basket_id):
    item = BookBasket.objects.get(id_=books.basket_id)
    item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

firstproject/mainapp/views.py
from django.shortcuts import render

from mainapp.models import ProductCategory, Books


def index(request):
    context = {
        'page_title': 'главная'
    }
    return render(request, 'mainapp/index.html', context)


def catalog(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories': categories,
        'page_title': 'каталог'
    }
    return render(request, 'mainapp/catalog.html', context)


def catalog_page(request, category_pk):
    books = Books.objects.filter(category_id=category_pk)
    context = {
        'books': books,
        'page_title': 'страница каталога'
    }
    return render(request, 'mainapp/catalog_page.html', context)


def books_page(request, pk):
    books = Books.objects.get(pk=pk)
    context = {
    'books': books,
    'page_title': 'книги'
    }
    return render(request, 'mainapp/course_page.html', context)

firstproject/authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"аутентификация"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/style.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

firstproject/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="login-form">
       <div class="form-title">Вход в систему</div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="войти">
        </form>
        <br>
        <a class="btn btn-info form-control" href="{% url 'auth:register' %}">
            зарегистрироваться
        </a>
    </div>
{% endblock %}

firstproject/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="register-form">
        <div class="form-title">Регистрация</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="зарегистрироваться">
        </form>
    </div>
{% endblock %}

firstproject/basketapp/templates/basketapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"книги"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/style.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="main-menu">
    <ul>
        <li>
            <a href="{% url 'main:index' %}">Главная</a>
        </li>
        <li>
            <a href="{% url 'main:catalog' %}">Каталог книг</a>
        </li>
        <li>
            <a href="{% url 'basket:index' %}">Корзина</a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
</div>
{% block content %}
{% endblock %}
</body>
</html>

firstproject/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}

{% block content %}
    <div class="basket">
    <h1>Ваша корзина</h1>
    <ul>
        {% for item in object_list %}
            <li>
                {{ item.to_html|safe }}
                <a href="{% url 'basket:remove' item.pk  %}">
            </li>
    </ul>
    </div>
{% endblock %}

firstproject/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"книги"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/style.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="main-menu">
    <ul>
        <li>
            <a href="{% url 'main:index' %}">Главная</a>
        </li>
        <li>
            <a href="{% url 'main:catalog' %}">Каталог книг</a>
        </li>
        <li>
            <a href="{% url 'basket:index' %}">Корзина</a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
</div>
            <ul class="books-menu">
                    <li><a href="">Художественная литература</a></li>
                    <li><a href="">Научная литература</a></li>
                    <li><a href="">Психология</a></li>
                    <li><a href="">Романы</a></li>
            </ul>
<h1>Интернет-магазин "Книжечка"</h1>
    <img src="static/img/1.jpg">
{% block content %}
{% endblock %}
</body>
</html>

firstproject/mainapp/templates/mainapp/books_page.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Книги</h1>
    <p class="books-name">
        {{ books.name }}
    </p>
    <p class="books-desc">
        описание: {{ books.desc }}
    </p>
    <a href="{% url 'basket:add' books.id %}"
        class="btn btn-success">
            добавить
    </a>
{% endblock %}